packages:
  - packages/*
  - '!playground'

catalog:
  pqueue: ^0.3.1

catalogs:
  dev:
    '@changesets/cli': ^2.29.7
    '@commitlint/config-conventional': ^20.0.0
    '@eslint/js': ^9.37.0
    '@iconify/json': ^2.2.394
    '@iconify/types': ^2.0.0
    '@microsoft/api-extractor': ^7.53.1
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-terser': ^0.4.4
    '@rollup/plugin-typescript': ^12.1.4
    '@types/node': ^24.7.1
    '@typescript-eslint/eslint-plugin': ^8.46.0
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    commitlint: ^20.1.0
    eslint: ^9.37.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import: ^2.32.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-vue: ^10.5.0
    globals: ^16.4.0
    husky: ^9.1.7
    jiti: ^2.6.1
    jsdom: ^27.0.0
    lint-staged: ^16.2.3
    prettier: ^3.6.2
    prettier-eslint: ^16.4.2
    rollup: ^4.52.4
    rollup-plugin-dts: ^6.2.3
    rollup-plugin-esbuild: ^6.2.1
    rollup-plugin-visualizer: ^6.0.4
    sass: ^1.93.2
    tinyglobby: ^0.2.15
    tsx: ^4.20.6
    typescript: ^5.9.3
    typescript-eslint: ^8.46.0
    unplugin-auto-import: ^20.2.0
    unplugin-icons: ^22.4.2
    unplugin-vue-components: ^29.1.0
    vite: ^7.1.9
    vite-plugin-css-injected-by-js: ^3.5.2
    vite-plugin-vue-devtools: ^8.0.2
    vue-eslint-parser: ^10.2.0
    vue-tsc: ^3.1.1
  test:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vue/test-utils': ^2.4.6
    msw: ^2.11.5
    vitest: ^3.2.4
    vitest-browser-vue: ^1.1.0
  tools:
    '@babel/types': ^7.28.4
    '@types/hash-sum': ^1.0.2
    '@types/hast': ^3.0.4
    '@types/lodash.merge': ^4.6.9
    '@types/three': ^0.180.0
    axios: ^1.12.2
    csstype: ^3.1.3
    dayjs: ^1.11.18
    dexie: ^4.2.1
    hash-sum: ^2.0.0
    hotkeys-js: ^3.13.15
    lodash.merge: ^4.6.2
    nanoid: ^5.1.6
    p-queue: ^9.0.0
    rfdc: ^1.4.1
    serialize-error: ^12.0.0
    shiki: ^3.13.0
    style-value-types: ^5.1.2
    sucrase: ^3.35.0
    three: ^0.180.0
    three-mesh-bvh: ^0.9.1
    type-fest: ^5.0.1
  vue:
    '@vueuse/core': ^13.9.0
    element-plus: ^2.11.4
    pinia: ^3.0.3
    unocss: ^66.5.3
    vue: ^3.5.22
    vue-i18n: ^11.1.12
    vue-router: ^4.5.1

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
