import { ComponentLabel, PropsType, RawComponent } from "../../../types"

export default {
  label: "el-date-picker",
  desc: "element-plus@el-date-picker",
  props: {
    "model-value": {
      type: [PropsType.Number, PropsType.String, PropsType.JSON],
      desc: "绑定值，如果它是数组，长度应该是 2",
      default: "",
      allowEmpty: true,
      finalType: PropsType.String,
    },
    readonly: {
      type: PropsType.Boolean,
      desc: "只读",
      default: false,
    },
    disabled: {
      type: PropsType.Boolean,
      desc: "禁用",
      default: false,
    },
    size: {
      type: PropsType.Enum,
      enums: ["large", "default", "small"],
      desc: "输入框尺寸",
      allowEmpty: true,
    },
    editable: {
      type: PropsType.Boolean,
      desc: "文本框可输入",
      default: true,
    },
    clearable: {
      type: PropsType.Boolean,
      desc: "是否显示清除按钮",
      default: true,
    },
    placeholder: {
      type: PropsType.String,
      desc: "非范围选择时的占位内容",
      default: "",
    },
    "start-placeholder": {
      type: PropsType.String,
      desc: "范围选择时开始日期的占位内容",
      allowEmpty: true,
    },
    "end-placeholder": {
      type: PropsType.String,
      desc: "范围选择时结束日期的占位内容",
      allowEmpty: true,
    },
    type: {
      type: PropsType.Enum,
      enums: [
        "year",
        "years",
        "month",
        "months",
        "date",
        "dates",
        "datetime",
        "week",
        "datetimerange",
        "daterange",
        "monthrange",
        "yearrange",
      ],
      desc: "显示类型",
      default: "date",
    },
    format: {
      type: PropsType.String,
      desc: "显示在输入框中的格式",
      default: "YYYY-MM-DD",
      allowEmpty: true,
    },
    "popper-class": {
      type: PropsType.String,
      desc: "DatePicker 下拉框的类名",
      allowEmpty: true,
    },
    "popper-options": {
      type: PropsType.JSON,
      desc: "自定义 popper 选项，更多请参考 popper.js",
      default: JSON.stringify({}),
    },
    "range-separator": {
      type: PropsType.String,
      desc: "选择范围时的分隔符",
      default: "-",
    },
    "default-value": {
      type: PropsType.JSON,
      desc: "可选，选择器打开时默认显示的时间",
      allowEmpty: true,
    },
    "default-time": {
      type: PropsType.JSON,
      desc: "范围选择时选中日期所使用的当日内具体时刻",
      allowEmpty: true,
    },
    "value-format": {
      type: PropsType.String,
      desc: "可选，绑定值的格式。不指定则绑定值为 Date 对象",
      allowEmpty: true,
    },
    id: {
      type: [PropsType.String, PropsType.JSON],
      desc: "等价于原生 input id 属性",
      allowEmpty: true,
      finalType: PropsType.String,
    },
    name: {
      type: [PropsType.String, PropsType.JSON],
      desc: "等价于原生 input name 属性",
      default: "",
      finalType: PropsType.String,
    },
    "unlink-panels": {
      type: PropsType.Boolean,
      desc: "在范围选择器里取消两个日期面板之间的联动",
      default: false,
    },
    "prefix-icon": {
      type: PropsType.Icon,
      desc: "自定义前缀图标 如果 type 的值是 TimeLikeType，那么就是 Clock，不然就是 Calendar",
      allowEmpty: true,
    },
    // "clear-icon": {
    //   type: [PropsType.String, PropsType.JSON],
    //   desc: "自定义清除图标",
    //   default: "CircleClose",
    //   finalType: PropsType.String,
    // },
    "validate-event": {
      type: PropsType.Boolean,
      desc: "是否触发表单验证",
      default: true,
    },
    "disabled-date": {
      type: PropsType.Function,
      desc: "一个用来判断该日期是否被禁用的函数，接受一个 Date 对象作为参数。应该返回一个 Boolean 值。",
      allowEmpty: true,
      args: ["data"],
      returnType: "boolean",
    },
    shortcuts: {
      type: PropsType.JSON,
      desc: "设置快捷选项，需要传入数组对象",
      default: JSON.stringify([]),
    },
    "cell-class-name": {
      type: PropsType.Function,
      desc: "设置自定义类名",
      allowEmpty: true,
      args: ["data"],
      returnType: "boolean",
    },
    teleported: {
      type: PropsType.Boolean,
      desc: "是否将 date-picker 的下拉列表插入至 body 元素",
      default: true,
    },
    "empty-values": {
      type: PropsType.JSON,
      desc: "组件的空值配置 参考 config-provider",
      default: JSON.stringify([]),
      version: "2.7.0",
    },
    "value-on-clear": {
      type: [PropsType.String, PropsType.Number, PropsType.Boolean, PropsType.Function],
      desc: "清空选项的值 参考 config-provider",
      allowEmpty: true,
      version: "2.7.0",
      finalType: PropsType.String,
    },
    "fallback-placements": {
      type: PropsType.JSON,
      desc: "Tooltip 可用的 positions 请查看 popper.js 文档",
      allowEmpty: true,
      version: "2.8.4",
    },
    placement: {
      type: PropsType.Enum,
      enums: [
        "top",
        "top-start",
        "top-end",
        "bottom",
        "bottom-start",
        "bottom-end",
        "left",
        "left-start",
        "left-end",
        "right",
        "right-start",
        "right-end",
      ],
      desc: "下拉框出现的位置",
      default: "bottom",
      version: "2.8.4",
    },
  },
  events: {
    change: {
      name: "change",
      desc: "用户确认选定的值时触发",
      args: ["value"],
    },
    blur: {
      name: "blur",
      desc: "在组件 Input 失去焦点时触发",
      args: ["event"],
    },
    focus: {
      name: "focus",
      desc: "在组件 Input 获得焦点时触发",
      args: ["event"],
    },
    clear: {
      name: "clear",
      desc: "可清空的模式下用户点击清空按钮时触发",
      args: [],
      version: "2.7.7",
    },
    "calendar-change": {
      name: "calendar-change",
      desc: "在日历所选日期更改时触发",
      args: ["value"],
    },
    "panel-change": {
      name: "panel-change",
      desc: "当日期面板改变时触发",
      args: ["value"],
    },
    "visible-change": {
      name: "visible-change",
      desc: "当 DatePicker 的下拉列表出现/消失时触发",
      args: ["visible"],
    },
  },
  slots: {
    default: {
      label: ComponentLabel.NULL,
      desc: "自定义单元格内容",
      props: {},
    },
    "range-separator": {
      label: ComponentLabel.NULL,
      desc: "自定义范围分割符内容",
      props: {},
    },
    "prev-month": {
      label: ComponentLabel.NULL,
      desc: "上个月的图标",
      props: {},
      version: "2.8.0",
    },
    "next-month": {
      label: ComponentLabel.NULL,
      desc: "下个月的图标",
      props: {},
      version: "2.8.0",
    },
    "prev-year": {
      label: ComponentLabel.NULL,
      desc: "上一年图标",
      props: {},
      version: "2.8.0",
    },
    "next-year": {
      label: ComponentLabel.NULL,
      desc: "下一年图标",
      props: {},
      version: "2.8.0",
    },
  },
} as RawComponent
