import { ComponentLabel, PropsType, RawComponent } from "../../../types"
export default {
  label: "el-select-v2",
  desc: "element-plus@el-select-v2",
  props: {
    "model-value": {
      type: [PropsType.String, PropsType.Number, PropsType.Boolean, PropsType.JSON],
      desc: "选中项绑定值",
      allowEmpty: true,
    },
    options: {
      type: PropsType.JSON,
      desc: "选项的数据源，value 的 key 和 label 可以通过 props 自定义",
      default: JSON.stringify([]),
    },
    props: {
      type: PropsType.JSON,
      desc: "配置选项，具体看下表",
      allowEmpty: true,
      version: "2.4.2",
    },
    multiple: {
      type: PropsType.Boolean,
      desc: "是否多选",
      default: false,
    },
    disabled: {
      type: PropsType.Boolean,
      desc: "是否禁用",
      default: false,
    },
    "value-key": {
      type: PropsType.String,
      desc: "作为 value 唯一标识的键名，绑定值为对象类型时必填",
      default: "value",
    },
    size: {
      type: PropsType.Enum,
      enums: ["large", "default", "small"],
      desc: "组件大小",
      default: "",
    },
    clearable: {
      type: PropsType.Boolean,
      desc: "是否可以清空选项",
      default: false,
    },
    "clear-icon": {
      type: [PropsType.String, PropsType.JSON],
      desc: "自定义清除图标",
      default: "CircleClose",
      finalType: PropsType.String,
    },
    "collapse-tags": {
      type: PropsType.Boolean,
      desc: "多选时是否将选中值按文字的形式展示",
      default: false,
    },
    "multiple-limit": {
      type: PropsType.Number,
      desc: "多选时可被选择的最大数目。当被设置为0时，可被选择的数目不设限",
      default: 0,
    },
    name: {
      type: PropsType.String,
      desc: "选择器的原生name属性",
      allowEmpty: true,
    },
    effect: {
      type: [PropsType.Enum, PropsType.String],
      desc: "tooltip 主题，内置了 dark / light 两种",
      enums: ["dark", "light"],
      default: "light",
      finalType: PropsType.Enum,
    },
    autocomplete: {
      type: PropsType.String,
      desc: "自动完成选择输入",
      default: "off",
    },
    placeholder: {
      type: PropsType.String,
      desc: "占位文字",
      default: "Please select",
    },
    filterable: {
      type: PropsType.Boolean,
      desc: "是否可筛选",
      default: false,
    },
    "allow-create": {
      type: PropsType.Boolean,
      desc: "是否允许创建新条目，当使用该属性时，filterable必须设置为true",
      default: false,
    },
    "filter-method": {
      type: PropsType.Function,
      desc: "自定义筛选方法",
      allowEmpty: true,
      args: ["value"],
      returnType: "any",
    },
    loading: {
      type: PropsType.Boolean,
      desc: "是否从远程加载数据",
      default: false,
    },
    "loading-text": {
      type: PropsType.String,
      desc: "从服务器加载数据时显示的文本，默认为“Loading”",
      allowEmpty: true,
    },
    "reserve-keyword": {
      type: PropsType.Boolean,
      desc: "筛选时，是否在选择选项后保留关键字",
      default: true,
    },
    "no-match-text": {
      type: PropsType.String,
      desc: "搜索条件无匹配时显示的文字，也可以使用 empty 插槽设置，默认是 “No matching data'”",
      allowEmpty: true,
    },
    "no-data-text": {
      type: PropsType.String,
      desc: "当在没有数据时显示的文字，你同时可以使用empty插槽进行设置",
      default: "No Data",
    },
    "popper-class": {
      type: PropsType.String,
      desc: "选择器下拉菜单的自定义类名",
      default: "",
    },
    teleported: {
      type: PropsType.Boolean,
      desc: "是否使用 teleport。设置成 true则会被追加到 append-to 的位置",
      default: true,
    },
    "append-to": {
      type: PropsType.String,
      desc: "下拉框挂载到哪个 DOM 元素",
      allowEmpty: true,
      version: "2.8.8",
    },
    persistent: {
      type: PropsType.Boolean,
      desc: "当下拉选择器未被激活并且persistent设置为false，选择器会被删除",
      default: true,
    },
    "popper-options": {
      type: PropsType.JSON,
      desc: "popper.js parameters",
      default: JSON.stringify({}),
    },
    "automatic-dropdown": {
      type: PropsType.Boolean,
      desc: "对于不可搜索的 Select，是否在输入框获得焦点后自动弹出选项菜单",
      default: false,
    },
    "fit-input-width": {
      type: [PropsType.Boolean, PropsType.Number],
      desc: "无论下拉框的宽度是否与输入框相同，如果值为number，则宽度是固定的",
      default: true,
      version: "2.9.2",
    },
    height: {
      type: PropsType.Number,
      desc: "下拉菜单的高度，每一个选项为34px",
      default: 274,
    },
    "item-height": {
      type: PropsType.Number,
      desc: "下拉项的高度",
      default: 34,
    },
    "scrollbar-always-on": {
      type: PropsType.Boolean,
      desc: "是否总是展示滚动条",
      default: false,
    },
    remote: {
      type: PropsType.Boolean,
      desc: "是否从服务器获取数据",
      default: false,
    },
    "remote-method": {
      type: PropsType.Function,
      desc: "当输入值发生变化时触发的函数。它的参数就是当前的输入值。当filterable设置为 true 时才会生效",
      allowEmpty: true,
      args: ["value"],
      returnType: "any",
    },
    "validate-event": {
      type: PropsType.Boolean,
      desc: "是否触发表单验证",
      default: true,
    },
    offset: {
      type: PropsType.Number,
      desc: "下拉面板偏移量",
      default: 12,
      version: "2.8.8",
    },
    "show-arrow": {
      type: PropsType.Boolean,
      desc: "下拉菜单的内容是否有箭头",
      default: true,
      version: "2.8.8",
    },
    placement: {
      type: PropsType.Enum,
      enums: [
        "top",
        "top-start",
        "top-end",
        "bottom",
        "bottom-start",
        "bottom-end",
        "left",
        "left-start",
        "left-end",
        "right",
        "right-start",
        "right-end",
      ],
      desc: "下拉框出现的位置",
      default: "bottom-start",
    },
    "fallback-placements": {
      type: PropsType.JSON,
      desc: "dropdown 可用的 positions 请查看popper.js 文档",
      default: JSON.stringify(["bottom-start", "top-start", "right", "left"]),
      version: "2.5.6",
    },
    "collapse-tags-tooltip": {
      type: PropsType.Boolean,
      desc: "当鼠标悬停于折叠标签的文本时，是否显示所有选中的标签。只有当 collapse-tags 设置为 true 时才会生效",
      default: false,
      version: "2.3.0",
    },
    "max-collapse-tags": {
      type: PropsType.Number,
      desc: "需要显示的 Tag 的最大数量。只有当 collapse-tags 设置为 true 时才会生效",
      default: 1,
      version: "2.3.0",
    },
    "tag-type": {
      type: PropsType.Enum,
      enums: ["success", "info", "warning", "danger"],
      desc: "标签类型",
      default: "info",
      version: "2.5.0",
    },
    "tag-effect": {
      type: PropsType.Enum,
      enums: ["dark", "light", "plain"],
      desc: "标签效果",
      default: "light",
      version: "2.7.7",
    },
    "aria-label": {
      type: PropsType.String,
      desc: "等价于原生 input aria-label 属性",
      allowEmpty: true,
      version: "2.5.0",
    },
    "empty-values": {
      type: PropsType.JSON,
      desc: "组件的空值配置 参考config-provider",
      allowEmpty: true,
      version: "2.7.0",
    },
    "value-on-clear": {
      type: [PropsType.String, PropsType.Number, PropsType.Boolean, PropsType.Function],
      desc: "清空选项的值 参考 config-provider",
      allowEmpty: true,
      version: "2.7.0",
      finalType: PropsType.String,
    },
    tabindex: {
      type: [PropsType.String, PropsType.Number],
      desc: "input 的 tabindex",
      allowEmpty: true,
      version: "2.9.0",
      finalType: PropsType.Number,
    },
  },
  events: {
    change: {
      name: "change",
      desc: "当所选值更改时触发，参数是当前选中的值",
      args: ["value"],
    },
    "visible-change": {
      name: "visible-change",
      desc: "当下拉菜单出现/消失时触发器, 当它出现时, 参数将是 true, 否则将是 false",
      args: ["visible"],
    },
    "remove-tag": {
      name: "remove-tag",
      desc: "当一个标签在多个模式下被移除时触发，参数将被移除标签值",
      args: ["tag"],
    },
    clear: {
      name: "clear",
      desc: "可清空的单选模式下用户点击清空按钮时触发",
      args: [],
    },
    blur: {
      name: "blur",
      desc: "当选择器的输入框失去焦点时触发",
      args: ["event"],
    },
    focus: {
      name: "focus",
      desc: "当选择器的输入框获得焦点时触发",
      args: ["event"],
    },
  },
  slots: {
    default: {
      label: ComponentLabel.NULL,
      desc: "自定义 Option 模板",
      props: {},
    },
    header: {
      label: ComponentLabel.NULL,
      desc: "下拉列表顶部的内容",
      props: {},
      version: "2.5.2",
    },
    footer: {
      label: ComponentLabel.NULL,
      desc: "下拉列表底部的内容",
      props: {},
      version: "2.5.2",
    },
    empty: {
      label: ComponentLabel.NULL,
      desc: "自定义当选项为空时的内容",
      props: {},
    },
    prefix: {
      label: ComponentLabel.NULL,
      desc: "输入框的前缀",
      props: {},
    },
    tag: {
      label: ComponentLabel.NULL,
      desc: "select 组件自定义标签内容",
      props: {},
      version: "2.5.0",
    },
    loading: {
      label: ComponentLabel.NULL,
      desc: "select 组件自定义 loading内容",
      props: {},
      version: "2.5.2",
    },
    label: {
      label: ComponentLabel.NULL,
      desc: "select 组件自定义标签内容",
      props: {},
      version: "2.7.4",
    },
  },
} as RawComponent
