import { ComponentLabel, PropsType, RawComponent } from "../../../types"
export default {
  label: "el-select",
  desc: "element-plus@el-select",
  props: {
    "model-value": {
      type: [PropsType.String, PropsType.Number, PropsType.Boolean, PropsType.JSON],
      desc: "选中项绑定值",
      allowEmpty: true,
    },
    multiple: {
      type: PropsType.Boolean,
      desc: "是否多选",
      default: false,
    },
    disabled: {
      type: PropsType.Boolean,
      desc: "是否禁用",
      default: false,
    },
    "value-key": {
      type: PropsType.String,
      desc: "作为 value 唯一标识的键名，绑定值为对象类型时必填",
      default: "value",
    },
    size: {
      type: PropsType.Enum,
      enums: ["large", "default", "small"],
      desc: "输入框尺寸",
      allowEmpty: true,
    },
    clearable: {
      type: PropsType.Boolean,
      desc: "是否可以清空选项",
      default: false,
    },
    "collapse-tags": {
      type: PropsType.Boolean,
      desc: "多选时是否将选中值按文字的形式展示",
      default: false,
    },
    "collapse-tags-tooltip": {
      type: PropsType.Boolean,
      desc: "当鼠标悬停于折叠标签的文本时，是否显示所有选中的标签。要使用此属性，collapse-tags属性必须设定为 true",
      default: false,
      version: "2.3.0",
    },
    "multiple-limit": {
      type: PropsType.Number,
      desc: "multiple 属性设置为 true 时，代表多选场景下用户最多可以选择的项目数，为 0 则不限制",
      default: 0,
    },
    name: {
      type: PropsType.String,
      desc: "Select 输入框的原生 name 属性",
      allowEmpty: true,
    },
    effect: {
      type: [PropsType.Enum, PropsType.String],
      enums: ["dark", "light"],
      desc: "tooltip 主题，内置了 dark / light 两种",
      default: "light",
      finalType: PropsType.Enum,
    },
    autocomplete: {
      type: PropsType.String,
      desc: "Select 输入框的原生 autocomplete 属性",
      default: "off",
    },
    placeholder: {
      type: PropsType.String,
      desc: "占位符，默认为“Select”",
      allowEmpty: true,
    },
    filterable: {
      type: PropsType.Boolean,
      desc: "Select 组件是否可筛选",
      default: false,
    },
    "allow-create": {
      type: PropsType.Boolean,
      desc: "是否允许用户创建新条目，只有当 filterable 设置为 true 时才会生效",
      default: false,
    },
    "filter-method": {
      type: PropsType.Function,
      desc: "自定义筛选方法",
      allowEmpty: true,
      args: ["value"],
      returnType: "any",
    },
    remote: {
      type: PropsType.Boolean,
      desc: "其中的选项是否从服务器远程加载",
      default: false,
    },
    "remote-method": {
      type: PropsType.Function,
      desc: "自定义远程搜索方法",
      allowEmpty: true,
      args: ["value"],
      returnType: "any",
    },
    "remote-show-suffix": {
      type: PropsType.Boolean,
      desc: "远程搜索方法显示后缀图标",
      default: false,
    },
    loading: {
      type: PropsType.Boolean,
      desc: "是否正在从远程获取数据",
      default: false,
    },
    "loading-text": {
      type: PropsType.String,
      desc: "从服务器加载数据时显示的文本，默认为“Loading”",
      allowEmpty: true,
    },
    "no-match-text": {
      type: PropsType.String,
      desc: "搜索条件无匹配时显示的文字，也可以使用 empty 插槽设置，默认是 “No matching data'”",
      allowEmpty: true,
    },
    "no-data-text": {
      type: PropsType.String,
      desc: "无选项时显示的文字，也可以使用 empty 插槽设置自定义内容，默认是 “No data”",
      allowEmpty: true,
    },
    "popper-class": {
      type: PropsType.String,
      desc: "选择器下拉菜单的自定义类名",
      default: "",
    },
    "reserve-keyword": {
      type: PropsType.Boolean,
      desc: "当 multiple 和 filterable被设置为 true 时，是否在选中一个选项后保留当前的搜索关键词",
      default: true,
    },
    "default-first-option": {
      type: PropsType.Boolean,
      desc: "是否在输入框按下回车时，选择第一个匹配项。需配合 filterable 或 remote 使用",
      default: false,
    },
    teleported: {
      type: PropsType.Boolean,
      desc: "是否使用 teleport。设置成 true则会被追加到 append-to 的位置",
      default: true,
    },
    "append-to": {
      type: PropsType.String,
      desc: "下拉框挂载到哪个 DOM 元素",
      allowEmpty: true,
      version: "2.8.4",
    },
    persistent: {
      type: PropsType.Boolean,
      desc: "当下拉选择器未被激活并且persistent设置为false，选择器会被删除",
      default: true,
    },
    "automatic-dropdown": {
      type: PropsType.Boolean,
      desc: "对于不可搜索的 Select，是否在输入框获得焦点后自动弹出选项菜单",
      default: false,
    },
    "clear-icon": {
      type: PropsType.Icon,
      desc: "自定义清除图标",
      allowEmpty: true,
    },
    "fit-input-width": {
      type: PropsType.Boolean,
      desc: "下拉框的宽度是否与输入框相同",
      default: false,
    },
    "suffix-icon": {
      type: PropsType.Icon,
      desc: "自定义后缀图标组件",
      allowEmpty: true,
    },
    "tag-type": {
      type: PropsType.Enum,
      enums: ["success", "info", "warning", "danger"],
      desc: "标签类型",
      default: "info",
    },
    "tag-effect": {
      type: PropsType.Enum,
      enums: ["dark", "light", "plain"],
      desc: "标签效果",
      default: "light",
      version: "2.7.7",
    },
    "validate-event": {
      type: PropsType.Boolean,
      desc: "是否触发表单验证",
      default: true,
    },
    offset: {
      type: PropsType.Number,
      desc: "下拉面板偏移量",
      default: 12,
      version: "2.8.8",
    },
    "show-arrow": {
      type: PropsType.Boolean,
      desc: "下拉菜单的内容是否有箭头",
      default: true,
      version: "2.8.8",
    },
    placement: {
      type: PropsType.Enum,
      enums: [
        "top",
        "top-start",
        "top-end",
        "bottom",
        "bottom-start",
        "bottom-end",
        "left",
        "left-start",
        "left-end",
        "right",
        "right-start",
        "right-end",
      ],
      desc: "下拉框出现的位置",
      default: "bottom-start",
      version: "2.2.17",
    },
    "fallback-placements": {
      type: PropsType.JSON,
      desc: "dropdown 可用的 positions 请查看popper.js 文档",
      default: JSON.stringify(["bottom-start", "top-start", "right", "left"]),
      version: "2.5.6",
    },
    "max-collapse-tags": {
      type: PropsType.Number,
      desc: "需要显示的 Tag 的最大数量 只有当 collapse-tags 设置为 true 时才会生效",
      default: 1,
      version: "2.3.0",
    },
    "popper-options": {
      type: PropsType.JSON,
      desc: "popper.js 参数",
      default: JSON.stringify({}),
    },
    "aria-label": {
      type: PropsType.String,
      desc: "等价于原生 input aria-label 属性",
      allowEmpty: true,
    },
    "empty-values": {
      type: PropsType.JSON,
      desc: "组件的空值配置 参考config-provider",
      allowEmpty: true,
      version: "2.7.0",
    },
    "value-on-clear": {
      type: [PropsType.String, PropsType.Number, PropsType.Boolean, PropsType.Function],
      desc: "清空选项的值 参考 config-provider",
      allowEmpty: true,
      version: "2.7.0",
      finalType: PropsType.String,
      args: [],
    },
    tabindex: {
      type: [PropsType.String, PropsType.Number],
      desc: "input 的 tabindex",
      allowEmpty: true,
      version: "2.9.0",
      finalType: PropsType.Number,
    },
  },
  events: {
    change: {
      name: "change",
      desc: "选中值发生变化时触发",
      args: ["value"],
    },
    "visible-change": {
      name: "visible-change",
      desc: "下拉框出现/隐藏时触发",
      args: ["visible"],
    },
    "remove-tag": {
      name: "remove-tag",
      desc: "多选模式下移除tag时触发",
      args: ["tag"],
    },
    clear: {
      name: "clear",
      desc: "可清空的单选模式下用户点击清空按钮时触发",
      args: [],
    },
    blur: {
      name: "blur",
      desc: "当 input 失去焦点时触发",
      args: ["event"],
    },
    focus: {
      name: "focus",
      desc: "当 input 获得焦点时触发",
      args: ["event"],
    },
    "popup-scroll": {
      name: "popup-scroll",
      desc: "下拉滚动时触发",
      args: ["event"],
      version: "2.9.4",
    },
  },
  slots: {
    default: {
      label: ComponentLabel.NULL,
      desc: "option 组件列表",
      props: {},
      children: ["el-option", "el-option-group"],
    },
    header: {
      label: ComponentLabel.NULL,
      desc: "下拉列表顶部的内容",
      props: {},
      version: "2.4.3",
    },
    footer: {
      label: ComponentLabel.NULL,
      desc: "下拉列表底部的内容",
      props: {},
      version: "2.4.3",
    },
    prefix: {
      label: ComponentLabel.NULL,
      desc: "Select 组件头部内容",
      props: {},
    },
    empty: {
      label: ComponentLabel.NULL,
      desc: "无选项时的列表",
      props: {},
    },
    tag: {
      label: ComponentLabel.NULL,
      desc: "select 组件自定义标签内容",
      props: {},
      version: "2.5.0",
    },
    loading: {
      label: ComponentLabel.NULL,
      desc: "select 组件自定义 loading内容",
      props: {},
      version: "2.5.2",
    },
    label: {
      label: ComponentLabel.NULL,
      desc: "select 组件自定义标签内容",
      props: {},
      version: "2.7.4",
    },
  },
} as RawComponent
